---
# =============================================================================
# Password set to: openstack (base64: b3BlbnN0YWNr)
# Apply: oc apply -f novasecret.yaml
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: libvirt-secret
  namespace: openstack
type: Opaque
data:
  LibvirtPassword: b3BlbnN0YWNr
